### ISSUE TITLE
Items that need to be added for looting

### ISSUE THREAD

**Issue by dsblack115** [nmsmith22389/HotLoot#17]
Quest: Commander Domitille's Helm (although I don't think it is labeled as a quest item when looted)
Skinning: Unbroken Tooth, Unbroken Claw
![wowscrnshot_030617_102015](https://cloud.githubusercontent.com/assets/22847171/23616109/9e609f52-0256-11e7-8b33-a02b16ceaf2f.jpg)
![wowscrnshot_030617_102025](https://cloud.githubusercontent.com/assets/22847171/23616108/9e5c6b9e-0256-11e7-8276-0fed8b91b7d2.jpg)
![wowscrnshot_030617_102045](https://cloud.githubusercontent.com/assets/22847171/23616107/9e5b6d52-0256-11e7-9e6b-89ca13a5cdde.jpg)

**Comment by nmsmith22389** [comment]
Thanks I'll look into adding them! If there are any other items or filter you think should be added please let me know!

**Comment by dsblack115** [comment]
I'll need to look, there are some others which delete but I'm not sure if it is because a checkbox needs to be ticked or what.  They are Motes of Life, Earth, Harmony (I think).  

Also, is there a way to move the HL messages to a different frame?  I have a separate loot frame to manage clutter, but HL posts in the main frame.

**Comment by dsblack115** [comment]
Another thing that I thought about on the loot monitor.  For Ancient Mana (7.1.5) and Nethershards (new in 7.2) although they don't actually get looted into the bags, there is a total amount.  Is there a way to have the total amount displayed in the loot monitor when it is looted, like whenever I skin something, it'll display the total amount in bags.  This is just a little convenience type thing, I can easily see how much I have, but just thought I'd run it by you to see if this can somehow be added in the loot monitor.

**Comment by dsblack115** [comment]
Addition: Legion Ammunition

This is part of a world quest, but gets deleted upon loot.  Added to inclusion list for now.

**Comment by nmsmith22389** [comment]
* There should be a filter for looting motes which should work.
* I can try to add an option for the output channel.
* For the Ancient Mana etc. I can look into it... If it technically counts as loot or currency I should be able to track it. Otherwise, I'm not sure.
* I'll look into Legion Ammunition too.

And the problem with a lot of these, Unbroken Tooth for example, is that most people would consider it a skinning item but behind the scenes its not actually labeled as one which is Blizzards problem and it makes things harder for me.

Until I get a lot of these items added in I suggest adding them to your include list. Also if you disable skinning mode it won't delete items. You can also disable it then set a modifier key with the next option which makes it so when you hold the key it will temporarily enable skinning mode but **only** when you are looting with the key held down.

I'll keep you updated on what I have working. If you ever want to try/test out an unreleased version you can always download from the `develop` branch and use that. It will have the newest features as it gets updated as I add things. **Be warned though, these are unstable and may not always work as intended.**

**Comment by dsblack115** [comment]
Ancient Mana, Nethershard are labeled as tokens.  For some reason Legionfall War Supplies don't show up anywhere, I have to look how much I have when it's looted.  But that's a UI issue, not an HL issue.
![2017-03-31](https://cloud.githubusercontent.com/assets/22847171/24573326/e205c39c-164f-11e7-8c45-7bf93e5e9af4.png)

**Comment by nmsmith22389** [comment]
ok I've got it now to where, for any currency/token, it will show you how many are looted and how many you have if you have the "Show Total in Bags" option check. I still need to overhaul the options though. If you'd like to try it you can dl the `develop` branch.

**Comment by nmsmith22389** [comment]
All currency (ancient mana etc) should be included in the latest available version along with the leather stuff. Thanks!
