### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Takamoko** [nmsmith22389/HotLoot#18]
I just discovered your addon and it's the first, which worked for me. I want to exclude so items from beeing looted and I tried some other addons without luck (they all had different problems).

Your addons looks promising and works, but it also has some inconveniences:

- The german translation is horrible. It looks like it's created by an earlier version of google translate. I'm using enUS.lua to understand some of the options. When I have some spare time, I'll start to create some better german text.

- The position of the loot window (HotLoot anchor) is not saved between sessions. 

- The addon should disable the WoW autoloot option or show a warning, if it's enabled (I saw some addons, which do that, e.g. an addon to will turn it on while fishing).

Regards
Thakan

**Comment by Takamoko** [comment]
I checked multiple chars. Some chars had the problem with the anchor position (reset to center), some chars don't ... I'll create new profiles and retry it...

Regards
Thakan

**Comment by nmsmith22389** [comment]
Hello and thank you so much for noticing HotLoot!
I will do my best to answer your questions...

1) Translations depend completely on the community to translate and thus some are incomplete. If you are able to, contributing goes a long ways towards helping. Just let me know when you are ready and I will make you a translator and you can add them at https://wow.curseforge.com/projects/hotloot/localization

    You should also know that very soon *(next few days)* a **brand new** version will be coming out that is much much better and has some pretty amazing improvements! One of the big ones is that it will not rely on translations in order for it to work properly. It will loot perfectly no matter the language after the update. Also, after the update the only thing that will need to be translated is the option names. If you are looking to contribute you should really wait until after the update as many of the words in the localization now will be gone and it won't take nearly as much work.
2) This is something that has also been completely fixed in the upcoming update along with a revamped theme system that will let you customize how it looks even more.
3) There is actually a note at the top in the options saying they should be disabled. However, I agree that it could be done better whether it's doing it with the addon or making the notice more noticeable. I will look into what it will take to do it automatically.

Really this new version makes the addon a million times better and fixes just about everything! I'm actually looking for a few testers so if you'd like to get your hands on it early just let me know! Thanks!
